
import { CardData, Theme } from './types';

export const DEFAULT_VALID_ACCESS_CODES: string[] = ['COUPLE123', 'AMOUR2024', 'LABTEST', 'SOURCECODE', 'ANNAETMAXIME'];
export const ADMIN_SECRET_CODE = 'ADMIN2024';

export const CARDS: CardData[] = [
  // Thème 1: NousDeux - Réapprendre à connaître l'autre (25 cartes)
  { id: 1, theme: Theme.NousDeux, question: 'Nomme ses meilleurs amis.' },
  { id: 2, theme: Theme.NousDeux, question: 'Cite sa musique préférée.' },
  { id: 3, theme: Theme.NousDeux, question: 'Liste ses films préférés.' },
  { id: 4, theme: Theme.NousDeux, question: 'Décris la première impression que tu lui as faite (de manière détaillée).' },
  { id: 5, theme: Theme.NousDeux, question: 'Nomme un de ses loisirs.' },
  { id: 6, theme: Theme.NousDeux, question: 'Où est-il/elle né(e) ?' },
  { id: 7, theme: Theme.NousDeux, question: 'Raconte en détails ce que l\'autre a fait hier.' },
  { id: 8, theme: Theme.NousDeux, question: 'Votre date d\'anniversaire de mariage.' },
  { id: 9, theme: Theme.NousDeux, question: 'Le membre de sa famille qu\'il/elle préfère.' },
  { id: 10, theme: Theme.NousDeux, question: 'Ses fleurs préférées.' },
  { id: 11, theme: Theme.NousDeux, question: 'Son moment préféré pour les câlins.' },
  { id: 12, theme: Theme.NousDeux, question: 'Ses plats préférés.' },
  { id: 13, theme: Theme.NousDeux, question: 'Comment il/elle préfère passer sa soirée.' },
  { id: 14, theme: Theme.NousDeux, question: 'Sa couleur préférée.' },
  { id: 15, theme: Theme.NousDeux, question: 'Les cadeaux qu\'il/elle préfère recevoir.' },
  { id: 16, theme: Theme.NousDeux, question: 'Son restaurant favori.' },
  { id: 17, theme: Theme.NousDeux, question: 'La radio qu\'il/elle écoute dans la voiture.' },
  { id: 18, theme: Theme.NousDeux, question: 'Ses desserts préférés.' },
  { id: 19, theme: Theme.NousDeux, question: 'Son numéro de téléphone portable (Pourquoi il est important pour lui/elle).' },
  { id: 20, theme: Theme.NousDeux, question: 'Son genre de livres préféré.' },
  { id: 21, theme: Theme.NousDeux, question: 'Sa fête préférée.' },
  { id: 22, theme: Theme.NousDeux, question: 'Le compliment qu\'il/elle préfère entendre.' },
  { id: 23, theme: Theme.NousDeux, question: 'Ce qui le/la fait rire aux éclats.' },
  { id: 24, theme: Theme.NousDeux, question: 'Décris son style vestimentaire idéal.' },
  { id: 25, theme: Theme.NousDeux, question: 'S\'il/elle pouvait avoir un super-pouvoir, lequel choisirait-il/elle et pourquoi ?' },

  // Thème 2: Confidences - Des choses que l'on ne s'est peut-être jamais raconté (25 cartes)
  { id: 26, theme: Theme.Confidences, question: 'Dis ce qui le stresse actuellement.' },
  { id: 27, theme: Theme.Confidences, question: 'Cite les noms des gens qui m\'énervent (et pourquoi, sans jugement).' },
  { id: 28, theme: Theme.Confidences, question: 'Raconte ses rêves les plus chers (personnels).' },
  { id: 29, theme: Theme.Confidences, question: 'Raconte les trois périodes les plus heureuses de sa vie.' },
  { id: 30, theme: Theme.Confidences, question: 'Raconte l\'événement le plus traumatisant que l\'autre ait vécu dans son enfance.' },
  { id: 31, theme: Theme.Confidences, question: 'Nomme ses espoirs et aspirations dans la vie (personnelles, non liées au couple).' },
  { id: 32, theme: Theme.Confidences, question: 'Décris ses préoccupations actuelles.' },
  { id: 33, theme: Theme.Confidences, question: 'Sa plus grande peur.' },
  { id: 34, theme: Theme.Confidences, question: 'Le domaine dans lequel il/elle se sent le plus compétent(e) (et pourquoi).' },
  { id: 35, theme: Theme.Confidences, question: 'Ce qu\'il/elle aimerait améliorer chez lui/elle.' },
  { id: 36, theme: Theme.Confidences, question: 'Son plus beau souvenir d\'enfance.' },
  { id: 37, theme: Theme.Confidences, question: 'Ses plus belles vacances (celles qui l\'ont le plus marqué).' },
  { id: 38, theme: Theme.Confidences, question: 'La manière de le/la réconforter quand il/elle est triste ou en colère.' },
  { id: 39, theme: Theme.Confidences, question: 'Son épisode le plus humiliant (et comment il/elle l\'a vécu).' },
  { id: 40, theme: Theme.Confidences, question: 'Deux personnes qu\'il/elle admire (et pourquoi).' },
  { id: 41, theme: Theme.Confidences, question: 'Un miracle (petit ou grand) qui lui est arrivé.' },
  { id: 42, theme: Theme.Confidences, question: 'Ce qu\'il/elle aimerait qu\'on retienne de lui/elle à la fin de sa vie.' },
  { id: 43, theme: Theme.Confidences, question: 'Ses "démons" intérieurs ou ses luttes personnelles.' },
  { id: 44, theme: Theme.Confidences, question: 'Le plus difficile dans ses interactions avec ses parents.' },
  { id: 45, theme: Theme.Confidences, question: 'Ce que vous lui avez dit qui l\'a le plus blessé (et comment le réparer).' },
  { id: 46, theme: Theme.Confidences, question: 'Ce qui l\'empêche d\'obtenir ce qu\'il/elle désire le plus dans sa vie.' },
  { id: 47, theme: Theme.Confidences, question: 'Quel est son regret le plus profond ?' },
  { id: 48, theme: Theme.Confidences, question: 'Quel talent caché l\'autre possède-t-il/elle que tu connais ?' },
  { id: 49, theme: Theme.Confidences, question: 'S\'il/elle pouvait changer une chose à son passé, quelle serait-elle ?' },
  { id: 50, theme: Theme.Confidences, question: 'Quel conseil donnerait-il/elle à son \'lui\' plus jeune ?' },
  
  // Thème 3: Avenir - Capacité à rêver ensemble et à avoir des projets d'avenir (25 cartes)
  { id: 51, theme: Theme.Avenir, question: 'Explique sa philosophie de vie (et comment elle s\'applique au couple).' },
  { id: 52, theme: Theme.Avenir, question: 'Décris son attitude vis-à-vis de la religion (et comment elle impacte votre couple).' },
  { id: 53, theme: Theme.Avenir, question: 'Comment il/elle utiliserait ses gains au Loto (pour le couple et/ou la famille).' },
  { id: 54, theme: Theme.Avenir, question: 'Nomme la personne qu\'il/elle aimerait devenir (en tant qu\'individu et partenaire).' },
  { id: 55, theme: Theme.Avenir, question: 'Ce qu\'il/elle aimerait le plus améliorer dans votre couple.' },
  { id: 56, theme: Theme.Avenir, question: 'Sa situation idéale de couple dans 5 ans.' },
  { id: 57, theme: Theme.Avenir, question: 'Les prochains événements importants de sa vie (et comment vous pouvez le/la soutenir).' },
  { id: 58, theme: Theme.Avenir, question: 'Son boulot idéal d\'après toi (et comment cela changerait votre vie de couple).' },
  { id: 59, theme: Theme.Avenir, question: 'Le projet le plus fou qu\'il/elle aimerait réaliser avec toi.' },
  { id: 60, theme: Theme.Avenir, question: 'Quelle est la prochaine grande aventure que vous aimeriez vivre ensemble ?' },
  { id: 61, theme: Theme.Avenir, question: 'Quelle compétence aimeriez-vous développer ensemble en tant que couple ?' },
  { id: 62, theme: Theme.Avenir, question: 'Si vous pouviez déménager n\'importe où, où iriez-vous et pourquoi ?' },
  { id: 63, theme: Theme.Avenir, question: 'Quelle tradition aimeriez-vous créer ou renforcer dans votre couple/famille ?' },
  { id: 64, theme: Theme.Avenir, question: 'Quel est le plus grand défi que vous aimeriez relever ensemble ?' },
  { id: 65, theme: Theme.Avenir, question: 'Comment aimeriez-vous vieillir ensemble ?' },
  { id: 66, theme: Theme.Avenir, question: 'Quel héritage aimeriez-vous laisser en tant que couple ?' },
  { id: 67, theme: Theme.Avenir, question: 'Si vous pouviez donner un conseil au couple que vous serez dans 10 ans, lequel serait-ce ?' },
  { id: 68, theme: Theme.Avenir, question: 'Quel est le voyage de rêve que vous n\'avez pas encore fait ?' },
  { id: 69, theme: Theme.Avenir, question: 'Comment imaginez-vous votre Chalom Bayit idéal ?' },
  { id: 70, theme: Theme.Avenir, question: 'Quel est le prochain grand apprentissage que vous aimeriez faire à deux ?' },
  { id: 71, theme: Theme.Avenir, question: 'Si vous deviez créer un "mantra" de couple, quel serait-il ?' },
  { id: 72, theme: Theme.Avenir, question: 'Quelle est la chose la plus importante que vous souhaitez enseigner à vos enfants (futurs ou actuels) sur le couple ?' },
  { id: 73, theme: Theme.Avenir, question: 'Comment aimeriez-vous célébrer votre prochain anniversaire de mariage ?' },
  { id: 74, theme: Theme.Avenir, question: 'Quelle cause ou projet communautaire aimeriez-vous soutenir ensemble ?' },
  { id: 75, theme: Theme.Avenir, question: 'Quel est votre plus grand rêve commun pour l\'avenir de votre couple ?' },
];